### ISSUE TITLE
Will this be updated for 2.0?

### ISSUE THREAD

**Issue by Bxmnx** [DerMistkaefer/Factorio_Fast-Long-Inserters#4]
This project seems to have been dormant for a while, will it be updated for 2.0?

**Comment by DerMistkaefer** [comment]
Hey @Bxmnx,

Thanks for the information about Factorio 2.0! I haven't played Factorio myself in quite a while, but I'm happy to update the mod if there's interest in seeing it work with the latest version.

I'll try to find some time to get it done today, but if that doesn't work out, I'll aim to get to it on Monday, as I'll be traveling over the weekend.

**Comment by DerMistkaefer** [comment]
Hey @Bxmnx,

I had some time today and updated the mod to be compatible with Factorio 2.0.
